<!DOCTYPE HTML>
<html style="margin: 0; padding: 0; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline;">
   <head style="margin: 0; padding: 0;">
   <meta charset="utf-8" style="margin: 0; padding: 0;">
   <script src="/js/jquery.js" style="margin: 0; padding: 0;"></script>
</head><body style="margin: 0; padding: 0; color: black; font-size: 100%; background: white; line-height: 1; border: 0; font-family: inherit; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline;">
   <h1 id="mail_title" style="margin: 0; padding: 0; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline; text-align: center;">Вы совершили покупку в магазине Apple tree!</h1>
   <div id="cart" style="margin: 20px auto 0; padding: 0; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline; text-align: center;">
         <table style="border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; margin: 0 auto; outline: 0; padding: 0; vertical-align: baseline; border-collapse: collapse; border-spacing: 0; text-align: center; width: 700px;"><tr class="head" style="margin: 0; padding: 0; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline;"><td colspan="2" style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0; margin-bottom: 10px;">Описание</td>
              <td style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0; margin-bottom: 10px;">Цена</td>
              <td style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0; margin-bottom: 10px;">Количество</td>
              <td style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0; margin-bottom: 10px;">Всего</td>
            </tr>
            {foreach $cart item=good}
            <tr style="margin: 0; padding: 0; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline;"><td class="image" style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0;">
                     <img src="{$host}/includes/uploads/{$good['image']}_s.jpg" style="margin: 5px; padding: 0; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline; width: 50px;"></td>
                  <td class="name" style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0;">
                     <a href="{$host}/card/{$good['id']}" style="margin: 0; padding: 0; color: inherit; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline; text-decoration: none;">{$good['name']}</a>
                  </td>
                  <td class="price" style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0;">{$good['price']} руб.</td>
                  <td class="quantity" style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0;">{$good['count']}</td>
                  <td class="price" style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0;">{$good['total']} руб.</td>
                </tr>
                {/foreach}
               <tr class="head" style="margin: 0; padding: 0; border: 0; font-family: inherit; font-size: 100%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline;"><td colspan="4" style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0; margin-bottom: 10px;">
               </td>
               <td style="margin: 0; padding: 10px; font-weight: inherit; text-align: left; border: 1px #ddd solid; font-family: inherit; font-size: 100%; font-style: inherit; outline: 0; vertical-align: middle; border-left: 0; border-right: 0; margin-bottom: 10px;">Total: {$total} руб.</td>
             </tr></table><a href="{$host}/cart_confirm/?h={$hash}&m={$email}&cn={$cart_num}" class="white_button big_button" style="margin: 0; padding: 3px; color: inherit; border: 1px black solid; font-family: inherit; font-size: 90%; font-style: inherit; font-weight: inherit; outline: 0; vertical-align: baseline; display: inline-block; margin-top: 30px; min-width: 90px; background: white; cursor: pointer; text-decoration: none;">Подтвердить заказ</a>
      </div>
   </body></html>
